### ISSUE TITLE
looping through folders

### ISSUE THREAD

**Issue by omarkr8** [mbhall88/ontime#12]
Hi, 

inexperienced in bash and want to use ontime for barcoded nanopore data. hoping i could get help building a loop of some sort?

the file structure looks like :

.
├── dir_A
│   ├── file1.fastq
│   └── file2.fastq
├── dir_B
│   ├── file1.fastq
│   └── file2.fastq

├── dir_C
│   ├── file1.fastq
│   └── file2.fastq

└── dir_D
    ├── file1.fastq
    └── file2.fastq

im trying to loop through the folders to subset the fastqs at several time points from 0-4h,0-8h,0-16h, etc...
ideally the output should also state which timeframe, with a suffix. 
currently reading up on how to build the loop, but perhaps ontime already has some function for this?

**Comment by omarkr8** [comment]
im probably going to end up writing a loop in R (which im more proficient in) and seems that  i can call ontime using system2().

but perhaps a looping function will still be useful

**Comment by omarkr8** [comment]
I still cant code in bash, but im pretty okay with R.

so here's what i came up with (variables are intuitive enough i hope):


for (fx in 1:length(fastq_path)){
             inputfq <- fastq_path[fx]
      for (tx in c("4h","8h","16h","24h","48h","72h")){
                if(!dir.exists(file.path(name_dir, paste("ontime_",tx,sep = "")))) dir.create(file.path(name_dir, paste("ontime_",tx,sep = ""))) 
  outputfq <- paste(file.path(name_dir, paste("ontime_",tx,sep = "")),"/",gsub("all", tx ,basename(inputfq)),".gz", sep = "")
  system2("ontime", args = c(inputfq,  "--to",tx , "-o", outputfq) , stdout = TRUE)
  }
}

seems to be working quite well

**Comment by mbhall88** [comment]
So do you want a single fastq output for each timepoint? I.e. you want to combine all fastq files together and then get the 0-2h from the combined? Or the 0-2h for each separate fastq?
