### ISSUE TITLE
Timestamps from recent versions of dorado do not work

### ISSUE THREAD

**Issue by jfnjdoh** [mbhall88/ontime#2]
I had some pod5 files that I recalled with dorado, specifically dorado 0.4.1+6c4c636+cu118, and the way the times are written in the header is different than what it used to be and causes ontime to fail to find a start time.

Off the nanopore itself, the format is `start_time=2023-10-18T11:14:29.364595-04:00`

dorado doesn't return fastq by default so if I do `dorado basecaller <model> <pod5> | samtools -T '*' - > <fastq>`, the time is written as `st:Z:2023-10-18T15:14:29.687+00:00`.

**Comment by mbhall88** [comment]
Ah thanks for raising this @jfnjdoh. I'll update ontime so that it can handle these fastqs also

**Comment by mbhall88** [comment]
This is now supported in the latest version and I have added a small section to the readme about how users can extract ontime-compatible fastqs from the dorado BAM.

Thanks again for reporting.
