### ISSUE TITLE
Extract reads from BAM in version 0.3.0 / Could not read the header of the input file

### ISSUE THREAD

**Issue by pkerbs** [mbhall88/ontime#9]
Hi @mbhall88,
thank you for your work on that. I finally found some time to test it and unfortunately, I encountered an issue with this new version.
I just run the new version on a BAM file like this:
```
ontime test.bam --to 2h > test_2h.bam
```
and got this error message:
```
[2024-02-12T20:25:09Z INFO ] Extracting read start times...
[2024-02-12T20:25:14Z INFO ] Gathered start times for 146140 reads
[2024-02-12T20:25:14Z INFO ] First and last timestamps in the input are 2024-02-08T15:24:22.872Z and 2024-02-09T16:35:34.702Z
[2024-02-12T20:25:14Z INFO ] Extracting reads with a start time between 2024-02-08 15:24:22.872 and 2024-02-08 17:24:22.872...
Error: Could not read the header of the input file

Caused by:
    invalid BAM header
```
The BAM file was generated by Dorado v0.5.2 like this:
```
dorado basecaller \
  sup,5mCG_5hmCG \
  <path to pod5 files> \
  --reference ref/chm13v2.fa \
  --bandwidth 500,20000 \
  -Y
```

Did I execute it wrong somehow, or missed a parameter for the header?
Thanks in advance.
Kind regards,
Paul

_Originally posted by @pkerbs in https://github.com/mbhall88/ontime/issues/6#issuecomment-1939545584_

**Comment by mbhall88** [comment]
Thanks for picking this up. No idea how I didn't see this in testing. v0.3.1 has the fix

**Comment by pkerbs** [comment]
Thank you so much, works like a charm.
Waiting for the release on Bioconda :)

**Comment by mbhall88** [comment]
> Waiting for the release on Bioconda :)

Just merged, so shouldn't be too long
